imports:
    - php

filter:
    excluded_paths:
        - vendor/
        - tests/
        - .php-cs-fixer.dist.php
    
    # dependency_paths:
    #     - src/Entity/
        # - src/Repository/
        - src/Kernel.php

build:
    image: default-bionic
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                # command: "composer phpunit"
                command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
